### ISSUE TITLE
3d models of the objects

### ISSUE THREAD

**Issue by TontonTremblay** [wliu88/rail_semantic_grasping#1]
Do you guys have 3d models of the objects used in the dataset?

**Comment by wliu88** [comment]
Hey @TontonTremblay, sorry for the late response. We don't have complete 3d models of objects in the dataset. Our method directly uses partial point clouds of objects to infer appropriate grasps. However, we used everyday objects that you can easily get from Amazon. In addition, you can possibly build partial 3d models of objects from point cloud data included in our dataset. If you want to use a task-oriented grasping dataset with more complete point clouds of objects, you can take a look at another dataset we released recently: https://github.com/adithyamurali/TaskGrasp
